# Generated by Django 4.2.29 on 2026-04-02 16:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('action', models.CharField(max_length=100)),
                ('resource', models.CharField(max_length=120)),
                ('changes', models.JSONField(default=dict)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
        ),
        migrations.CreateModel(
            name='Bottleneck',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('road_priority_weight', models.FloatField(default=1.0)),
                ('district', models.CharField(max_length=120)),
                ('bottleneck_type', models.CharField(choices=[('intersection', 'Intersection'), ('bridge', 'Bridge'), ('school_zone', 'School Zone'), ('market', 'Market'), ('terminal', 'Terminal'), ('other', 'Other')], default='other', max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='WeatherData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('condition', models.CharField(choices=[('clear', 'Clear'), ('light_rain', 'Light Rain'), ('moderate_rain', 'Moderate Rain'), ('heavy_rain', 'Heavy Rain'), ('severe', 'Severe')], default='clear', max_length=30)),
                ('temperature', models.FloatField(default=0.0)),
                ('precipitation', models.FloatField(default=0.0)),
                ('weather_impact_factor', models.FloatField(default=1.0)),
            ],
            options={
                'indexes': [models.Index(fields=['timestamp', 'condition'], name='core_weathe_timesta_328124_idx')],
            },
        ),
        migrations.CreateModel(
            name='TrafficData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('traffic_severity_index', models.FloatField(default=0.0)),
                ('vehicle_count', models.IntegerField(default=0)),
                ('avg_speed', models.FloatField(default=0.0)),
                ('bottleneck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='traffic_data', to='core.bottleneck')),
            ],
        ),
        migrations.CreateModel(
            name='Scenario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('name', models.CharField(max_length=120, unique=True)),
                ('description', models.TextField(blank=True)),
                ('preset_parameters', models.JSONField(default=dict)),
                ('is_default', models.BooleanField(db_index=True, default=False)),
            ],
            options={
                'indexes': [models.Index(fields=['is_default', 'name'], name='core_scenar_is_defa_c9de15_idx')],
            },
        ),
        migrations.CreateModel(
            name='OptimizationRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('run_id', models.CharField(db_index=True, max_length=64, unique=True)),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('parameters', models.JSONField(default=dict)),
                ('fitness_scores', models.JSONField(default=list)),
                ('result_data', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='queued', max_length=20)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='optimization_runs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Officer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('name', models.CharField(max_length=255)),
                ('badge_number', models.CharField(max_length=40, unique=True)),
                ('shift', models.CharField(choices=[('morning', 'Morning'), ('afternoon', 'Afternoon'), ('night', 'Night')], max_length=20)),
                ('status', models.CharField(choices=[('available', 'Available'), ('deployed', 'Deployed'), ('off_duty', 'Off Duty'), ('unavailable', 'Unavailable')], default='available', max_length=20)),
                ('skills', models.JSONField(blank=True, default=list)),
                ('current_latitude', models.FloatField(blank=True, null=True)),
                ('current_longitude', models.FloatField(blank=True, null=True)),
            ],
            options={
                'indexes': [models.Index(fields=['badge_number'], name='core_office_badge_n_0a506b_idx'), models.Index(fields=['shift', 'status'], name='core_office_shift_60cef1_idx')],
            },
        ),
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('incident_type', models.CharField(choices=[('collision', 'Collision'), ('road_closure', 'Road Closure'), ('construction', 'Construction'), ('flooding', 'Flooding'), ('other', 'Other')], default='other', max_length=30)),
                ('severity', models.CharField(choices=[('critical', 'Critical'), ('major', 'Major'), ('minor', 'Minor')], max_length=20)),
                ('description', models.TextField()),
                ('photo_url', models.URLField(blank=True)),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('investigating', 'Investigating'), ('resolved', 'Resolved')], db_index=True, default='active', max_length=20)),
                ('bottleneck', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incidents', to='core.bottleneck')),
                ('reported_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reported_incidents', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Deployment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('shift', models.CharField(choices=[('morning', 'Morning'), ('afternoon', 'Afternoon'), ('night', 'Night')], max_length=20)),
                ('start_time', models.DateTimeField(db_index=True)),
                ('end_time', models.DateTimeField(db_index=True)),
                ('assignment_type', models.CharField(choices=[('static', 'Static Post'), ('mobile', 'Mobile Patrol'), ('response', 'Rapid Response')], default='static', max_length=20)),
                ('status', models.CharField(db_index=True, default='assigned', max_length=20)),
                ('bottleneck', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deployments', to='core.bottleneck')),
                ('officer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deployments', to='core.officer')),
            ],
        ),
        migrations.AddIndex(
            model_name='bottleneck',
            index=models.Index(fields=['district'], name='core_bottle_distric_69aa1d_idx'),
        ),
        migrations.AddIndex(
            model_name='bottleneck',
            index=models.Index(fields=['bottleneck_type'], name='core_bottle_bottlen_6da640_idx'),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='audit_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='trafficdata',
            index=models.Index(fields=['bottleneck', 'timestamp'], name='core_traffi_bottlen_7fdd7a_idx'),
        ),
        migrations.AddIndex(
            model_name='trafficdata',
            index=models.Index(fields=['timestamp'], name='core_traffi_timesta_e67b92_idx'),
        ),
        migrations.AddIndex(
            model_name='optimizationrun',
            index=models.Index(fields=['timestamp', 'status'], name='core_optimi_timesta_4a50df_idx'),
        ),
        migrations.AddIndex(
            model_name='incident',
            index=models.Index(fields=['timestamp'], name='core_incide_timesta_28c07d_idx'),
        ),
        migrations.AddIndex(
            model_name='incident',
            index=models.Index(fields=['severity', 'status'], name='core_incide_severit_7b1dce_idx'),
        ),
        migrations.AddIndex(
            model_name='incident',
            index=models.Index(fields=['bottleneck', 'status'], name='core_incide_bottlen_0e4605_idx'),
        ),
        migrations.AddIndex(
            model_name='deployment',
            index=models.Index(fields=['officer', 'start_time'], name='core_deploy_officer_a6dbbb_idx'),
        ),
        migrations.AddIndex(
            model_name='deployment',
            index=models.Index(fields=['bottleneck', 'start_time'], name='core_deploy_bottlen_a08454_idx'),
        ),
        migrations.AddIndex(
            model_name='deployment',
            index=models.Index(fields=['shift', 'status'], name='core_deploy_shift_c1ec26_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['timestamp'], name='core_auditl_timesta_80074f_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['resource', 'action'], name='core_auditl_resourc_662f69_idx'),
        ),
    ]
