# Generated by Django 4.2.29 on 2026-05-15 17:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_add_officer_user_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='POI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('poi_id', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('hospital', 'Hospital'), ('fire_station', 'Fire Station'), ('police_station', 'Police Station'), ('school', 'School'), ('other', 'Other')], default='other', max_length=30)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('icon_url', models.URLField(blank=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
            ],
        ),
        migrations.AddField(
            model_name='bottleneck',
            name='heatmap_tsi',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bottleneck',
            name='is_archived',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='bottleneck',
            name='tsi',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='incident',
            name='is_archived',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='incident',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='resolved_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='incident',
            name='bottleneck',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='incidents', to='core.bottleneck'),
        ),
        migrations.AlterField(
            model_name='incident',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('investigating', 'Investigating'), ('resolved', 'Resolved'), ('archived', 'Archived')], db_index=True, default='active', max_length=20),
        ),
        migrations.AddIndex(
            model_name='bottleneck',
            index=models.Index(fields=['is_archived'], name='core_bottle_is_arch_050c02_idx'),
        ),
        migrations.AddIndex(
            model_name='incident',
            index=models.Index(fields=['is_archived'], name='core_incide_is_arch_72776f_idx'),
        ),
        migrations.AddIndex(
            model_name='poi',
            index=models.Index(fields=['category'], name='core_poi_categor_fd0c90_idx'),
        ),
        migrations.AddIndex(
            model_name='poi',
            index=models.Index(fields=['is_active'], name='core_poi_is_acti_487a6b_idx'),
        ),
    ]
