# Generated by Django 4.2.29 on 2026-05-26 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auditlog_user_nullable'),
    ]

    operations = [
        migrations.AddField(
            model_name='deployment',
            name='source',
            field=models.CharField(choices=[('manual', 'Manual / ICTTMO'), ('optimized', 'GA Optimized')], db_index=True, default='manual', max_length=20),
        ),
    ]
