# Generated by Django 4.2.29 on 2026-05-31 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_add_deployment_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='poi',
            name='priority_boost',
            field=models.FloatField(default=1.0, help_text='Multiplier for nearby bottleneck priority (e.g. 1.5 = 50% boost)'),
        ),
    ]
