# Generated by Django 4.2.30 on 2026-08-15 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_add_poi_priority_boost'),
    ]

    operations = [
        migrations.AddField(
            model_name='bottleneck',
            name='max_officers_allowed',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='bottleneck',
            name='min_officers_required',
            field=models.IntegerField(default=2),
        ),
        migrations.AddConstraint(
            model_name='deployment',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False), ('status', 'assigned')), fields=('officer', 'shift'), name='unique_officer_shift_assignment'),
        ),
    ]
