# Generated by Django 4.2.29 on 2026-09-28 16:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0009_schedule_rules_and_remove_scenario'),
    ]

    operations = [
        migrations.AddField(
            model_name='optimizationrun',
            name='heartbeat_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='optimizationrun',
            name='task_id',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.CreateModel(
            name='ScheduleRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operational_date', models.DateField(db_index=True)),
                ('shift', models.CharField(choices=[('morning', 'Morning (6 AM - 2 PM)'), ('afternoon', 'Afternoon (2 PM - 10 PM)')], max_length=20)),
                ('published_at', models.DateTimeField()),
                ('effective_start', models.DateTimeField()),
                ('effective_end', models.DateTimeField()),
                ('idempotency_key', models.CharField(max_length=64, unique=True)),
                ('request_fingerprint', models.CharField(max_length=64)),
                ('previous_assignments', models.JSONField(default=list)),
                ('assignments', models.JSONField(default=list)),
                ('response', models.JSONField(default=dict)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='publications', to='core.optimizationrun')),
            ],
        ),
        migrations.AddField(
            model_name='deployment',
            name='revision',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='deployments', to='core.schedulerevision'),
        ),
    ]
