# Generated by Django 4.2.29 on 2026-09-29 14:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0011_bottleneck_staffing_periods'),
    ]

    operations = [
        migrations.AddField(
            model_name='deployment',
            name='override_reason',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.CreateModel(
            name='OfficerTimeBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('start_time', models.DateTimeField(db_index=True)),
                ('end_time', models.DateTimeField()),
                ('kind', models.CharField(choices=[('break', 'Break'), ('travel', 'Travel')], max_length=12)),
                ('note', models.CharField(blank=True, max_length=300)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('officer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.officer')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FieldObservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observed_at', models.DateTimeField(db_index=True)),
                ('actual_officers', models.PositiveIntegerField()),
                ('traffic', models.CharField(choices=[('free', 'Free'), ('moderate', 'Moderate'), ('heavy', 'Heavy'), ('critical', 'Critical')], max_length=12)),
                ('note', models.CharField(blank=True, max_length=1000)),
                ('required_officers', models.PositiveIntegerField()),
                ('scheduled_officers', models.PositiveIntegerField()),
                ('area_name', models.CharField(blank=True, max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bottleneck', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.bottleneck')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
